/**
 * scripts/deploy.ts
 * ──────────────────
 * Deploys MockUSDC, AuditLog, and BlackRiverBroker to the target network.
 * Prints the deployed addresses and writes them to .env.local for the agent layer.
 *
 * Usage:
 *   npx hardhat run scripts/deploy.ts --network localhost
 *   npx hardhat run scripts/deploy.ts --network tempo_testnet
 */

import { ethers } from "hardhat";
import * as fs from "fs";
import * as path from "path";

async function main() {
  const [deployer, brokerWallet, consumerWallet] = await ethers.getSigners();

  console.log("\n── Black River Phase 1 Deployment ────────────────────────");
  console.log(`Deployer:       ${deployer.address}`);
  console.log(`Broker wallet:  ${brokerWallet.address}`);
  console.log(`Consumer wallet:${consumerWallet.address}`);
  console.log(`Network:        ${(await ethers.provider.getNetwork()).name}`);

  // ── 1. MockUSDC ──────────────────────────────────────────────────────────
  console.log("\n[1/3] Deploying MockUSDC...");
  const MockUSDC = await ethers.getContractFactory("MockUSDC");
  const mockUSDC = await MockUSDC.deploy(deployer.address);
  await mockUSDC.waitForDeployment();
  const usdcAddr = await mockUSDC.getAddress();
  console.log(`      MockUSDC deployed → ${usdcAddr}`);

  // Mint tokens for demo participants
  const MINT_AMOUNT = ethers.parseUnits("10000", 6); // 10,000 USDC each
  await mockUSDC.mint(consumerWallet.address, MINT_AMOUNT);
  await mockUSDC.mint(brokerWallet.address, MINT_AMOUNT);
  console.log(`      Minted 10,000 mUSDC → consumer and broker wallets`);

  // ── 2. AuditLog ──────────────────────────────────────────────────────────
  console.log("\n[2/3] Deploying AuditLog...");
  const AuditLog = await ethers.getContractFactory("AuditLog");
  const auditLog = await AuditLog.deploy();
  await auditLog.waitForDeployment();
  const auditLogAddr = await auditLog.getAddress();
  console.log(`      AuditLog deployed → ${auditLogAddr}`);

  // ── 3. BlackRiverBroker ──────────────────────────────────────────────────
  console.log("\n[3/3] Deploying BlackRiverBroker...");
  const BlackRiverBroker = await ethers.getContractFactory("BlackRiverBroker");
  const broker = await BlackRiverBroker.deploy(
    usdcAddr,
    auditLogAddr,
    brokerWallet.address
  );
  await broker.waitForDeployment();
  const brokerAddr = await broker.getAddress();
  console.log(`      BlackRiverBroker deployed → ${brokerAddr}`);

  // Authorise broker contract to write to AuditLog
  await auditLog.setAuthorised(brokerAddr, true);
  await auditLog.setAuthorised(brokerWallet.address, true);
  console.log(`      AuditLog: authorised broker contract + wallet`);

  // Consumer approves broker contract to spend USDC (for demo)
  const mockUSDCAsConsumer = mockUSDC.connect(consumerWallet);
  await mockUSDCAsConsumer.approve(brokerAddr, ethers.parseUnits("5000", 6));
  console.log(`      Consumer approved 5,000 mUSDC spend for broker contract`);

  // ── Write .env.local ──────────────────────────────────────────────────────
  const envPath = path.join(__dirname, "..", ".env.local");
  const envContent = [
    `# Auto-generated by deploy.ts — ${new Date().toISOString()}`,
    `AUDIT_LOG_ADDRESS=${auditLogAddr}`,
    `BROKER_CONTRACT_ADDRESS=${brokerAddr}`,
    `MOCK_USDC_ADDRESS=${usdcAddr}`,
    `BROKER_WALLET=${brokerWallet.address}`,
    `CONSUMER_WALLET=${consumerWallet.address}`,
  ].join("\n");

  fs.writeFileSync(envPath, envContent + "\n");
  console.log(`\n      Contract addresses written to .env.local`);

  console.log("\n── Deployment complete ────────────────────────────────────");
  console.log(`  MockUSDC:          ${usdcAddr}`);
  console.log(`  AuditLog:          ${auditLogAddr}`);
  console.log(`  BlackRiverBroker:  ${brokerAddr}`);
  console.log("\nNext step:  python demo.py\n");
}

main().catch((err) => {
  console.error(err);
  process.exitCode = 1;
});
